language: python

python: 2.7

matrix:
  include:
    - env: TOX_ENV=py27
    - env: TOX_ENV=py35
    - env: TOX_ENV=py36

install:
  - pip install tox

script:
  - pip install -U setuptools
  - tox -e $TOX_ENV

after_success:
  - coveralls
