language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install requirements_dev.txt
  - python setup.py develop

script:
  - coverage run --source=selection -m runscript.cli test

after_success:
  - coveralls
